apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.43.1  # Official MongoDB Exporter image
          ports:
            - containerPort: 9216  # Default port exposed by MongoDB Exporter
          command:
            - "/mongodb_exporter"
            - "--mongodb.uri=mongodb://mongodb-service:27017"  # MongoDB URI
            - "--collect-all"  # Collect all metrics
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
spec:
  ports:
    - port: 9216
      targetPort: 9216
  selector:
    app: mongodb-exporter
