---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'springboot-app'
        static_configs:
          - targets: ['springboot-service:8080']
        metrics_path: '/actuator/prometheus'
        scheme: 'http'
      - job_name: 'mongodb'
        static_configs:
          - targets: [ 'mongodb-exporter:9216' ]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.43.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml   # Correct mount path for the prometheus.yml file
              subPath: prometheus.yml                     # Use subPath to mount only the prometheus.yml file
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config                   # The name of the ConfigMap
